In [ ]:
import pandas as pd
import numpy as np

In [ ]:
df = pd.read_csv('data.csv')
X = df.loc[:, df.columns != 'sentiment'].to_numpy()
y = df["sentiment"].to_numpy()

In [ ]:
# Import Library for splitting data
from sklearn.model_selection import train_test_split

# Split dataset into training set and test set
X_train, X_test, y_train, y_test = train_test_split(X,y, random_state = 50, test_size = 0.25)

# print the total number of training set (records)
print(np.shape(y_train))

# print the total number of test set (records)
print(np.shape(y_test))

(3164,)
(1055,)


In [ ]:
# Import Library for KNeighborsClassifier
from sklearn.neighbors import KNeighborsClassifier
# Create a training model KNeighborsClassifier
model_1 = KNeighborsClassifier()

#Create the SVM model
from sklearn.svm import SVC
model_2 = SVC(kernel = 'poly', random_state = 0)

# Creating Decision Tree Classifier
from sklearn import tree
from sklearn.tree import DecisionTreeClassifier
model_3 = DecisionTreeClassifier()

#Importing our MLPClassifier model
from sklearn.neural_network import MLPClassifier
#model initialization
model_4 = MLPClassifier(hidden_layer_sizes=(10,5), max_iter=2000, alpha=0.01, #try change hidden layer
                     solver='sgd', verbose=0,  random_state=121) #try verbode=0 to train with out logging

In [ ]:
model_1.fit(X_train, y_train)
model_2.fit(X_train, y_train)
model_3.fit(X_train, y_train)
model_4.fit(X_train, y_train)

MLPClassifier(alpha=0.01, hidden_layer_sizes=(10, 5), max_iter=2000,
              random_state=121, solver='sgd', verbose=0)

In [ ]:
from sklearn.metrics import confusion_matrix
from sklearn.metrics import f1_score

print("model 1")
print(model_1.score(X_test, y_test))
print(f1_score(y_test, model_1.predict(X_test)))
print(confusion_matrix(y_test, model_1.predict(X_test)))
print("model 2")
print(model_2.score(X_test, y_test))
print(f1_score(y_test, model_2.predict(X_test)))
print(confusion_matrix(y_test, model_2.predict(X_test)))
print("model 3")
print(model_3.score(X_test, y_test))
print(f1_score(y_test, model_3.predict(X_test)))
print(confusion_matrix(y_test, model_3.predict(X_test)))
print("model 4")
print(model_4.score(X_test, y_test))
print(f1_score(y_test, model_4.predict(X_test)))
print(confusion_matrix(y_test, model_4.predict(X_test)))

model 1
0.7706161137440758
0.8561236623067776
[[ 93 115]
 [127 720]]
model 2
0.8170616113744076
0.8967362225789193
[[ 24 184]
 [  9 838]]
model 3
0.8218009478672986
0.8937853107344633
[[ 76 132]
 [ 56 791]]
model 4
0.804739336492891
0.891005291005291
[[  7 201]
 [  5 842]]


NLTK testing

In [ ]:
import nltk
import pandas as pd
import numpy as np
from pprint import pprint
import re, unicodedata
from nltk.stem import WordNetLemmatizer

In [ ]:
nltk.download(["punkt"])
nltk.download('stopwords')
nltk.download('vader_lexicon')
nltk.download('wordnet')

stopwords = nltk.corpus.stopwords.words("english")
lemmatizer = WordNetLemmatizer()

[nltk_data] Downloading package punkt to /root/nltk_data...
[nltk_data]   Package punkt is already up-to-date!
[nltk_data] Downloading package stopwords to /root/nltk_data...
[nltk_data]   Package stopwords is already up-to-date!
[nltk_data] Downloading package vader_lexicon to /root/nltk_data...
[nltk_data]   Package vader_lexicon is already up-to-date!
[nltk_data] Downloading package wordnet to /root/nltk_data...
[nltk_data]   Package wordnet is already up-to-date!


In [ ]:
df = pd.read_csv('dataraw.csv')
listA = df["text"].values.tolist()
sentiment = df["sentiment"].values.tolist()
print(len(listA))
print(len(sentiment))

4227
4227


In [ ]:
listA[21]

'Ok, let’s see... \n\nA ton of water \nNon-perishable foods \nAmple beer and whiskey \nCandles and battery powered reading lights \nMore books than anyone could read in multiple lifetimes \nJack the Cat \n\nOk Hurricane Michael, I’m ready to take you on.'

In [ ]:
listB = []
listC = []
for i in listA:
  text = i.lower()
  text = re.sub(r'http\S+', '', text)
  text = re.sub(r'(\s)@\w+', r'\1', text)
  words = nltk.word_tokenize(text)
  words = [w for w in words if w.isalpha()]
  words = [w for w in words if w not in stopwords]
  words = [lemmatizer.lemmatize(w) for w in words]
  #pprint(words, width=79, compact=True)
  listB.append(words)
  listC.extend(words)

In [ ]:
print(len(listB))
print(len(listC))

4227
51783


In [ ]:
fd = nltk.FreqDist(listC)
fd.tabulate(10)

hurricane   michael      food  survivor      fema   furious       via     water     daily     beast 
     4374      4094      3277      2392      2377      2078      1052       752       683       671 


In [ ]:
from nltk.sentiment import SentimentIntensityAnalyzer
sia = SentimentIntensityAnalyzer()

In [ ]:
sia_list = list()
for i in listA:
  sia_list.append(sia.polarity_scores(i)["compound"])

In [ ]:
test = [i for i in sentiment if i == 0]
print(len(test))
print(len(sentiment))
percent = len(test) / len(sentiment)
print(percent)

888
4227
0.2100780695528744


In [ ]:
s0_listB = list()
s1_listB = list()
s0_listC = list()
s1_listC = list()

for i in range(len(sentiment)):
  if (sentiment[i] == 0):
    s0_listB.append(listB[i])
    s0_listC.extend(listB[i])
  elif (sentiment[i] == 1):
    s1_listB.append(listB[i])
    s1_listC.extend(listB[i])

In [ ]:
s0_fd = nltk.FreqDist(s0_listC)
s0_fd.tabulate(10)
s1_fd = nltk.FreqDist(s1_listC)
s1_fd.tabulate(10)

top_100_s0 = {word for word, count in s0_fd.most_common(100)}
top_100_s1 = {word for word, count in s1_fd.most_common(100)}

hurricane   michael      food     water      fema  survivor   furious       car   florida      help 
      958       902       609       231       229       215       177       167       134       128 
hurricane   michael      food  survivor      fema   furious       via     daily     beast     water 
     3416      3192      2668      2177      2148      1901       970       614       608       521 


In [ ]:
print(s0_fd.most_common(100))
print(top_100_s1)

[('hurricane', 958), ('michael', 902), ('food', 609), ('water', 231), ('fema', 229), ('survivor', 215), ('furious', 177), ('car', 167), ('florida', 134), ('help', 128), ('ride', 112), ('trump', 100), ('storm', 99), ('power', 97), ('via', 82), ('people', 81), ('safe', 69), ('daily', 69), ('area', 68), ('please', 64), ('beast', 63), ('get', 61), ('need', 61), ('city', 60), ('affected', 59), ('u', 57), ('safety', 55), ('panama', 55), ('like', 54), ('tip', 53), ('victim', 51), ('supply', 50), ('day', 50), ('good', 48), ('path', 47), ('free', 46), ('see', 45), ('panhandle', 45), ('one', 45), ('many', 45), ('rally', 45), ('take', 44), ('going', 44), ('vehicle', 44), ('usda', 42), ('ready', 41), ('tree', 40), ('video', 39), ('right', 39), ('offer', 39), ('time', 38), ('hit', 37), ('first', 37), ('without', 36), ('emergency', 36), ('stay', 35), ('go', 35), ('home', 35), ('everyone', 33), ('disaster', 31), ('keep', 31), ('busy', 31), ('look', 31), ('house', 31), ('family', 30), ('battery', 30),